const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.AJAX,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.TextBox.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Interpolação: 0},
	{letreiro: 0},
	{bgHome: 0},
	{telaPreta: 0},
	{btnNextLayout: 0},
	{letreiroHome: 0},
	{Mouse: 0},
	{bgEscolha: 0},
	{blackout: 0},
	{pergaminho: 0},
	{textEscolha: 0},
	{spriteRyojinEscolha: 0},
	{spriteLiangEscolha: 0},
	{spriteYukkiEscolha: 0},
	{spriteTakedaEscolha: 0},
	{nameRyojin: 0},
	{nameLiang: 0},
	{nameYukki: 0},
	{nameTakeda: 0},
	{bgDetalhesPersonagem: 0},
	{PlanoDeFundoEmBlocos: 0},
	{spritePersonagem: 0},
	{namePersonagem: 0},
	{textHistoria: 0},
	{textEstiloDeLuta: 0},
	{textArmas: 0},
	{btnEscolher: 0},
	{Texto: 0},
	{village: 0},
	{florest: 0},
	{village2: 0},
	{village3: 0},
	{village4: 0},
	{Teclado: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{player: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{feitico: 0},
	{health: 0},
	{Sprite: 0},
	{pts: 0},
	{gameOverText: 0},
	{rankingDeJogadores: 0},
	{nomeJogador: 0},
	{enviar: 0},
	{AJAX: 0},
	{voltar: 0},
	{Sólido: 0},
	{blocoInvisivelblocoInvisivelblocoInvisivelblocoInvisivel: 0},
	{personagemEscolhido: 0},
	{Score: 0},
	{Pontos: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	letreiro: class extends self.ISpriteInstance {},
	bgHome: class extends self.ISpriteInstance {},
	telaPreta: class extends self.ISpriteInstance {},
	btnNextLayout: class extends self.ISpriteInstance {},
	letreiroHome: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	bgEscolha: class extends self.ITiledBackgroundInstance {},
	blackout: class extends self.ITiledBackgroundInstance {},
	pergaminho: class extends self.ISpriteInstance {},
	textEscolha: class extends self.ITextInstance {},
	spriteRyojinEscolha: class extends self.ISpriteInstance {},
	spriteLiangEscolha: class extends self.ISpriteInstance {},
	spriteYukkiEscolha: class extends self.ISpriteInstance {},
	spriteTakedaEscolha: class extends self.ISpriteInstance {},
	nameRyojin: class extends self.ITextInstance {},
	nameLiang: class extends self.ITextInstance {},
	nameYukki: class extends self.ITextInstance {},
	nameTakeda: class extends self.ITextInstance {},
	bgDetalhesPersonagem: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	spritePersonagem: class extends self.ISpriteInstance {},
	namePersonagem: class extends self.ITextInstance {},
	textHistoria: class extends self.ITextInstance {},
	textEstiloDeLuta: class extends self.ITextInstance {},
	textArmas: class extends self.ITextInstance {},
	btnEscolher: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	village: class extends self.ISpriteInstance {},
	florest: class extends self.ISpriteInstance {},
	village2: class extends self.ISpriteInstance {},
	village3: class extends self.ISpriteInstance {},
	village4: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	player: class extends self.ISpriteInstance {},
	feitico: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	pts: class extends self.ITextInstance {},
	gameOverText: class extends self.ITextInstance {},
	rankingDeJogadores: class extends self.ITextInstance {},
	nomeJogador: class extends self.ITextInputInstance {},
	enviar: class extends self.IButtonInstance {},
	AJAX: class extends self.IInstance {},
	voltar: class extends self.IButtonInstance {},
	blocoInvisivelblocoInvisivelblocoInvisivelblocoInvisivel: class extends self.ISpriteInstance {}
}